version: '3'
services:
  vue3-ts-base-beta:
    container_name: vue3-ts-base-beta
    restart: always
    platform: linux/x86_64
    image: nginx
    volumes:
      - ./dist:/app
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 10001:80
